# CashCards

server:
  port: 8061

logging.level:
  com.webgenerals.cashcards: DEBUG
  org.springframework.security: DEBUG
  org.hibernate.SQL: DEBUG

spring.datasource.url: jdbc:h2:mem:cashcardsdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.sql.init.mode: always
spring.jpa.defer-datasource-initialization: true
spring.jpa.hibernate.ddl-auto: none